-------------------
-- CREATE TABLES --
-------------------

USE 'KuihDadar';

LOAD DATA INFILE 'data/staff.csv' 
INTO TABLE Staff
FIELDS TERMINATED BY ','
FIELDS ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'data/role_skill.csv' 
INTO TABLE Role_Skill
FIELDS TERMINATED BY ','
FIELDS ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'data/staff_skill.csv' 
INTO TABLE Staff_Skill
FIELDS TERMINATED BY ','
FIELDS ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'data/role.csv' 
INTO TABLE Role
FIELDS TERMINATED BY ','
FIELDS ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'data/Access_Control.csv' 
INTO TABLE Access_Rights
FIELDS TERMINATED BY ','
FIELDS ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'data/skill.csv' 
INTO TABLE Skill
FIELDS TERMINATED BY ','
FIELDS ENCLOSED BY '"'
LINES TERMINATED BY '\n'